name: majesticons
description: "A Flutter package providing over 1300 customizable icons, both in solid and line styles, for enriching your app's UI."
version: 1.0.0
homepage: https://github.com/sadreactonly/majesticons
repository: https://github.com/sadreactonly/majesticons

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: majesticons
      fonts:
        - asset: fonts/majesticons.ttf
